# -*- coding: utf-8 -*-
r"""v0.5 卡牌文案（自动生成，可用 gen_cards_v05.py 的 doc 重跑同步）。"""

ZH = {
    'DaJi': '造成 {Damage:diff()} 点伤害。',
    'FangYu': '获得 {Block:diff()} 点格挡。',
    'QiBi': '抽 {Cards:diff()} 张牌，获得 {Edge:diff()} 点笔锋。',
    'YunBi': '获得 {Block:diff()} 点格挡，获得 {Force:diff()} 点力道。',
    'ChengFu': '造成 {Damage:diff()} 点伤害。',
    'QingDian': '造成 {Damage:diff()} 点伤害，获得 {Edge:diff()} 点笔锋。',
    'DianRan': '获得 {Block:diff()} 点格挡，获得 {Edge:diff()} 点笔锋。',
    'WeiMang': '0 费，造成 {Damage:diff()} 点伤害。',
    'LuoDian': '0 费，获得 {Edge:diff()} 点笔锋。',
    'ShuBi': '抽 {Cards:diff()} 张牌。',
    'DianZhui': '造成 {Damage:diff()} 点伤害，抽 {Cards:diff()} 张牌。',
    'DianPo': '敌人失去 {StrengthLoss:diff()} 点力量，获得 {Edge:diff()} 点笔锋。',
    'HengXian': '造成 {Damage:diff()} 点伤害。',
    'ShuXian': '获得 {Block:diff()} 点格挡。',
    'GouXian': '获得 {Force:diff()} 点力道。',
    'LianXian': '造成 {Damage:diff()} 点伤害，获得 {Force:diff()} 点力道。',
    'BiZhi': '获得 {Block:diff()} 点格挡，获得 {Force:diff()} 点力道。',
    'ZhiBi': '造成 {Damage:diff()} 点伤害。',
    'ChangXian': '抽 {Cards:diff()} 张牌，获得 {Force:diff()} 点力道。',
    'PoMian': '造成 {Damage:diff()} 点伤害。',
    'DaMian': '获得 {Block:diff()} 点格挡。',
    'MoMian': '抽 {Cards:diff()} 张牌，获得 1 点能量。',
    'ManFu': '获得 {Block:diff()} 点格挡，造成 {Damage:diff()} 点伤害。',
    'KuoMian': '对所有敌人造成 {Damage:diff()} 点伤害。',
    'ChenMo': '获得 {MoYun:diff()} 点墨韵（跨回合累积）。',
    'DianJing': '0 费：获得 {Edge:diff()} 点笔锋，抽 {Cards:diff()} 张牌。',
    'DianShi': '获得 {Edge:diff()} 点笔锋。',
    'YiDian': '0 费：造成 {Damage:diff()} 点伤害，共 {Repeat:diff()} 次。',
    'LuoMo': '获得 {Block:diff()} 点格挡，获得 {Edge:diff()} 点笔锋。',
    'ShuSan': '弃 {Discard:diff()} 张牌，获得 {Edge:diff()} 点笔锋。',
    'QianMiao': '造成 {Damage:diff()} 点伤害；若你持有笔锋，额外造成 4 点。',
    'XiBi': '0 费：造成 {Damage:diff()} 点伤害，获得 {Edge:diff()} 点笔锋。',
    'DianYin': '抽 {Cards:diff()} 张牌，获得 {Edge:diff()} 点笔锋。',
    'MoDianV5': '造成 {Damage:diff()} 点伤害；获得等同你笔锋层数的格挡。',
    'DianPoXuKong': '造成 {Damage:diff()} 点伤害。',
    'HuiFeng': '0 费：造成 {Damage:diff()} 点伤害，失去 {BloodCost:diff()} 点生命。',
    'DianXianChengMian': '消耗所有笔锋，每 {QiPerMoYun:diff()} 点换 1 点墨韵。',
    'LiTouZhiBei': '获得 {Force:diff()} 点力道。',
    'YiBiHua': '造成 {Damage:diff()} 点伤害，获得 {Force:diff()} 点力道。',
    'ZongHeng': '获得 {Force:diff()} 点力道。本回合每次获得力道时额外 +{Bonus:diff()}。',
    'XianTiao': '造成 {Damage:diff()} 点伤害，抽 {Cards:diff()} 张牌。',
    'ZhiGuan': '造成 {Damage:diff()} 点伤害；若你的力道不低于 3，伤害翻倍。',
    'ChanSi': '获得 {Block:diff()} 点格挡，获得 {Force:diff()} 点力道。',
    'YunJinChengFeng': '获得 {Force:diff()} 点力道，抽 {Cards:diff()} 张牌。',
    'BiFengYiZhuan': '将你的力道翻倍（先 +{Force:diff()} 再叠加当前层数）。',
    'YiXianTian': '需力道不低于 5 才能打出。 造成 {Damage:diff()} 点伤害。[消耗]。',
    'ChuanZhenYinXian': '造成 {Damage:diff()} 点伤害；你每有 1 点力道，此伤害 +{PerForce:diff()}。',
    'ChangQuZhiRu': '造成 {Damage:diff()} 点伤害，获得 {Force:diff()} 点力道。',
    'LiDaoHuiLiu': '消耗所有力道，抽等同层数 +{Bonus:diff()} 的牌。',
    'PoMoV5': '对所有敌人造成 {Damage:diff()} 点伤害。',
    'DaPoMo': '对所有敌人造成 {Damage:diff()} 点伤害。',
    'ManZhiYunYan': '获得 {Block:diff()} 点格挡。',
    'WanHeQianYan': '获得 {Block:diff()} 点格挡。',
    'MoYunTianChengV5': '获得 {MoYun:diff()} 点墨韵，抽 {Cards:diff()} 张牌。',
    'NongMoZhongCai': '造成 {Damage:diff()} 点伤害；消耗 {MoYunCost:diff()} 点墨韵，此牌伤害 +{Bonus:diff()}。',
    'JuanZhou': '抽 {Cards:diff()} 张牌。',
    'PoTianV5': '消耗所有墨韵，每点对所有敌人造成 {PerMoYun:diff()} 点伤害。[消耗]。',
    'LiYaQianJun': '造成 {Damage:diff()} 点伤害。若你的墨韵不低于 10，此牌费用变为 0。',
    'MoJin': '需手牌不多于 1 张 才能打出。造成 {Damage:diff()} 点伤害。',
    'KuangCao': '抽 {Cards:diff()} 张牌，受到 5 点伤害。',
    'JieBi': '0 费：抽 {Cards:diff()} 张牌。 若你本回合打出过「回锋」，额外获得 1 点能量。',
    'XuZhi': '0 费：抽 {Cards:diff()} 张牌。',
    'WuShiWuZhong': '每回合最多触发 {Cap:diff()} 次： 你打出「点」牌时，抽 1 张牌。',
    'RunBi': '每当你打出一张「点」牌，获得 1 点能量（每回合上限 {Cap:diff()} 次）。',
    'DianJingZhiBi': '0 费：获得 {Edge:diff()} 点笔锋，抽 {Cards:diff()} 张牌。',
    'WanDianGuiYi': '造成 {Damage:diff()} 点伤害，共 {Repeat:diff()} 次。',
    'ShuMiYouZhi': '消耗所有笔锋，每点抽 1 张牌。',
    'HaoLi': '0 费：造成等同你笔锋 {PerEdge:diff()} 倍的伤害。',
    'DianShiChengJin': '获得 {Edge:diff()} 点笔锋。',
    'MoShou': '获得 {Block:diff()} 点格挡，再额外获得等于你笔锋 3 倍的格挡。',
    'LiTouZhiBeiV5': '每回合开始时获得 {Force:diff()} 点力道。',
    'TieHuaYinGou': '造成 {Damage:diff()} 点伤害，获得 {Force:diff()} 点力道。',
    'ZhongFeng': '获得 {Force:diff()} 点力道。',
    'TieXian': '造成等同你力道 {PerForce:diff()} 倍的伤害。',
    'XingYunLiuShui': '获得 {Force:diff()} 点力道，抽 {Cards:diff()} 张牌。',
    'BiLaoMoXiu': '消耗所有力道，每点获得 1 点能量。',
    'QianJunYiBi': '造成 {Damage:diff()} 点伤害，获得 {Force:diff()} 点力道。[消耗]。',
    'PoTianAbility': '墨韵不再削弱「点 / 线」牌，改为每满 5 层，你的「面」牌伤害 +{PerStep:diff()}。',
    'WanShanHongBian': '对所有敌人造成 {Damage:diff()} 点伤害。[消耗] 消耗 {MoYunCost:diff()} 点墨韵，改为 36 点。',
    'MoHai': '一次获得 {MoYun:diff()} 点墨韵，抽 {Cards:diff()} 张牌。',
    'ShanGaoShuiChang': '获得 {Block:diff()} 点格挡。',
    'ChangJuan': '抽 {Cards:diff()} 张牌，受到 6 点伤害。',
    'LiTouWanXiang': '造成「墨韵层数 ×{PerMoYun:diff()} + {Base:diff()}」点伤害。[消耗]。',
    'KaiTianPiDi': '造成 {Damage:diff()} 点伤害。[消耗] 若你的手牌为空，再对所有敌人造成 {EmptyBonus:diff()} 点伤害。',
    'JingShuiLiuShen': '获得 {MoYun:diff()} 点墨韵，抽 {Cards:diff()} 张牌。',
    'WanJieRuLinAncient': '每 {PerMoYun:diff()} 点墨韵，获得 1 点能量并抽 1 张牌。[消耗] 保留。★ 不直接造成伤害 —— 它把墨韵变成你继续运转的燃料。',
    'WuMingZhiShi': '将你的墨韵、笔锋、力道 全部清零，每清 2 层获得 {PerTwo:diff()} 点能量。[消耗] ★ 重置按钮：墨韵堆太高拖累了点/线时，用它换一波费用重新开始。',
    'TaDeLaiChu': '获得 {Force:diff()} 点力道。 ★ 她的身世没人说得清，但她说的话总能让人多出一分力气。',
    'HuoXuShiZhenDe': '造成 {Damage:diff()} 点伤害，抽 1 张牌。 ★ 传闻有真有假 —— 打出它抽到的那张牌，就当是「或许是真的」。',
    'Mi': '抽 {Cards:diff()} 张牌；若你的手牌不多于 1 张，改为抽 {EmptyDraw:diff()} 张。 ★ 「林」的身份一直是个谜 —— 你越接近答案，得到的越多。',
}

EN = {
    'DaJi': 'Deal {Damage:diff()} damage.',
    'FangYu': 'Gain {Block:diff()} Block.',
    'QiBi': 'Draw {Cards:diff()} card(s), Gain {Edge:diff()} Edge.',
    'YunBi': 'Gain {Block:diff()} Block, Gain {Force:diff()} Force.',
    'ChengFu': 'Deal {Damage:diff()} damage.',
    'QingDian': 'Deal {Damage:diff()} damage, Gain {Edge:diff()} Edge.',
    'DianRan': 'Gain {Block:diff()} Block, Gain {Edge:diff()} Edge.',
    'WeiMang': '0 费, Deal {Damage:diff()} damage.',
    'LuoDian': '0 费, Gain {Edge:diff()} Edge.',
    'ShuBi': 'Draw {Cards:diff()} card(s).',
    'DianZhui': 'Deal {Damage:diff()} damage, Draw {Cards:diff()} card(s).',
    'DianPo': 'enemy Lose {StrengthLoss:diff()} Strength, Gain {Edge:diff()} Edge.',
    'HengXian': 'Deal {Damage:diff()} damage.',
    'ShuXian': 'Gain {Block:diff()} Block.',
    'GouXian': 'Gain {Force:diff()} Force.',
    'LianXian': 'Deal {Damage:diff()} damage, Gain {Force:diff()} Force.',
    'BiZhi': 'Gain {Block:diff()} Block, Gain {Force:diff()} Force.',
    'ZhiBi': 'Deal {Damage:diff()} damage.',
    'ChangXian': 'Draw {Cards:diff()} card(s), Gain {Force:diff()} Force.',
    'PoMian': 'Deal {Damage:diff()} damage.',
    'DaMian': 'Gain {Block:diff()} Block.',
    'MoMian': 'Draw {Cards:diff()} card(s), Gain 1 Energy.',
    'ManFu': 'Gain {Block:diff()} Block, Deal {Damage:diff()} damage.',
    'KuoMian': 'Deal to ALL enemies {Damage:diff()} damage.',
    'ChenMo': 'Gain {MoYun:diff()} Ink（跨turn累积）.',
    'DianJing': '0 费：Gain {Edge:diff()} Edge, Draw {Cards:diff()} card(s).',
    'DianShi': 'Gain {Edge:diff()} Edge.',
    'YiDian': '0 费：Deal {Damage:diff()} damage, 共 {Repeat:diff()} time(s).',
    'LuoMo': 'Gain {Block:diff()} Block, Gain {Edge:diff()} Edge.',
    'ShuSan': '弃 {Discard:diff()} card(s), Gain {Edge:diff()} Edge.',
    'QianMiao': 'Deal {Damage:diff()} damage；If you 持有Edge, 额外Deal 4 点.',
    'XiBi': '0 费：Deal {Damage:diff()} damage, Gain {Edge:diff()} Edge.',
    'DianYin': 'Draw {Cards:diff()} card(s), Gain {Edge:diff()} Edge.',
    'MoDianV5': 'Deal {Damage:diff()} damage；Gain 等同you Edge stack(s)数的Block.',
    'DianPoXuKong': 'Deal {Damage:diff()} damage.',
    'HuiFeng': '0 费：Deal {Damage:diff()} damage, Lose {BloodCost:diff()} 点HP.',
    'DianXianChengMian': 'Spend all Edge, per {QiPerMoYun:diff()} 点换 1 Ink.',
    'LiTouZhiBei': 'Gain {Force:diff()} Force.',
    'YiBiHua': 'Deal {Damage:diff()} damage, Gain {Force:diff()} Force.',
    'ZongHeng': 'Gain {Force:diff()} Force. this turnper time(s)Gain Force时额外 +{Bonus:diff()}.',
    'XianTiao': 'Deal {Damage:diff()} damage, Draw {Cards:diff()} card(s).',
    'ZhiGuan': 'Deal {Damage:diff()} damage；If you 的Forceor more 3, damage翻倍.',
    'ChanSi': 'Gain {Block:diff()} Block, Gain {Force:diff()} Force.',
    'YunJinChengFeng': 'Gain {Force:diff()} Force, Draw {Cards:diff()} card(s).',
    'BiFengYiZhuan': '将you 的Force翻倍（先 +{Force:diff()} 再叠加当前 stack(s)数）.',
    'YiXianTian': '需Forceor more 5 才能打出. Deal {Damage:diff()} damage. [Spend ].',
    'ChuanZhenYinXian': 'Deal {Damage:diff()} damage；you per 有 1 Force, 此damage +{PerForce:diff()}.',
    'ChangQuZhiRu': 'Deal {Damage:diff()} damage, Gain {Force:diff()} Force.',
    'LiDaoHuiLiu': 'Spend all Force, Draw 等同 stack(s)数 +{Bonus:diff()} 的牌.',
    'PoMoV5': 'Deal to ALL enemies {Damage:diff()} damage.',
    'DaPoMo': 'Deal to ALL enemies {Damage:diff()} damage.',
    'ManZhiYunYan': 'Gain {Block:diff()} Block.',
    'WanHeQianYan': 'Gain {Block:diff()} Block.',
    'MoYunTianChengV5': 'Gain {MoYun:diff()} Ink, Draw {Cards:diff()} card(s).',
    'NongMoZhongCai': 'Deal {Damage:diff()} damage；Spend {MoYunCost:diff()} Ink, 此牌damage +{Bonus:diff()}.',
    'JuanZhou': 'Draw {Cards:diff()} card(s).',
    'PoTianV5': 'Spend all Ink, per 点Deal to ALL enemies {PerMoYun:diff()} damage. [Spend ].',
    'LiYaQianJun': 'Deal {Damage:diff()} damage. If you 的Inkor more 10, 此牌费用变为 0.',
    'MoJin': '需hand不多于 1 张 才能打出. Deal {Damage:diff()} damage.',
    'KuangCao': 'Draw {Cards:diff()} card(s), Take 5 damage.',
    'JieBi': '0 费：Draw {Cards:diff()} card(s). If you this turn打出过「回锋」, 额外Gain 1 Energy.',
    'XuZhi': '0 费：Draw {Cards:diff()} card(s).',
    'WuShiWuZhong': 'per turnup to 触发 {Cap:diff()} time(s)： you 打出「点」牌时, Draw 1 card(s).',
    'RunBi': 'per 当you 打出一张「点」牌, Gain 1 Energy（per turn上限 {Cap:diff()} time(s)）.',
    'DianJingZhiBi': '0 费：Gain {Edge:diff()} Edge, Draw {Cards:diff()} card(s).',
    'WanDianGuiYi': 'Deal {Damage:diff()} damage, 共 {Repeat:diff()} time(s).',
    'ShuMiYouZhi': 'Spend all Edge, per 点Draw 1 card(s).',
    'HaoLi': '0 费：Deal 等同you Edge {PerEdge:diff()} 倍的damage.',
    'DianShiChengJin': 'Gain {Edge:diff()} Edge.',
    'MoShou': 'Gain {Block:diff()} Block, 再额外Gain 等于you Edge 3 倍的Block.',
    'LiTouZhiBeiV5': 'per turn开始时Gain {Force:diff()} Force.',
    'TieHuaYinGou': 'Deal {Damage:diff()} damage, Gain {Force:diff()} Force.',
    'ZhongFeng': 'Gain {Force:diff()} Force.',
    'TieXian': 'Deal 等同you Force {PerForce:diff()} 倍的damage.',
    'XingYunLiuShui': 'Gain {Force:diff()} Force, Draw {Cards:diff()} card(s).',
    'BiLaoMoXiu': 'Spend all Force, per 点Gain 1 Energy.',
    'QianJunYiBi': 'Deal {Damage:diff()} damage, Gain {Force:diff()} Force. [Spend ].',
    'PoTianAbility': 'Ink不再削弱「点 / 线」牌, 改为per 满 5 stack(s), you 的「面」牌damage +{PerStep:diff()}.',
    'WanShanHongBian': 'Deal to ALL enemies {Damage:diff()} damage. [Spend ] Spend {MoYunCost:diff()} Ink, 改为 36 点.',
    'MoHai': '一 time(s)Gain {MoYun:diff()} Ink, Draw {Cards:diff()} card(s).',
    'ShanGaoShuiChang': 'Gain {Block:diff()} Block.',
    'ChangJuan': 'Draw {Cards:diff()} card(s), Take 6 damage.',
    'LiTouWanXiang': 'Deal 「Ink stack(s)数 ×{PerMoYun:diff()} + {Base:diff()}」 damage. [Spend ].',
    'KaiTianPiDi': 'Deal {Damage:diff()} damage. [Spend ] If you 的handis empty, 再Deal to ALL enemies {EmptyBonus:diff()} damage.',
    'JingShuiLiuShen': 'Gain {MoYun:diff()} Ink, Draw {Cards:diff()} card(s).',
    'WanJieRuLinAncient': 'per {PerMoYun:diff()} Ink, Gain 1 Energy并Draw 1 card(s). [Spend ] 保留. ★ 不直接Deal damage —— 它把Ink变成you 继续运转的燃料.',
    'WuMingZhiShi': '将you 的Ink, Edge, Force 全部清零, per 清 2 stack(s)Gain {PerTwo:diff()} Energy. [Spend ] ★ 重置按钮：Ink堆太高拖累了点/线时, 用它换一波费用重新开始.',
    'TaDeLaiChu': 'Gain {Force:diff()} Force. ★ 她的身世没人说得清, 但她说的话总能让人多出一分力气.',
    'HuoXuShiZhenDe': 'Deal {Damage:diff()} damage, Draw 1 card(s). ★ 传闻有真有假 —— 打出它Draw 到的那 card(s), 就当是「或许是真的」.',
    'Mi': 'Draw {Cards:diff()} card(s)；If you 的hand不多于 1 张, 改为Draw {EmptyDraw:diff()} 张. ★ 「林」的身份一直是个谜 —— you 越接近答案, 得到的越多.',
}

TITLES_ZH = {
    'DaJi': '打击',
    'FangYu': '防御',
    'QiBi': '起笔',
    'YunBi': '运笔',
    'ChengFu': '成幅',
    'QingDian': '轻点',
    'DianRan': '点染',
    'WeiMang': '微芒',
    'LuoDian': '落点',
    'ShuBi': '数笔',
    'DianZhui': '点缀',
    'DianPo': '点破',
    'HengXian': '横线',
    'ShuXian': '竖线',
    'GouXian': '勾线',
    'LianXian': '连线',
    'BiZhi': '笔直',
    'ZhiBi': '直笔',
    'ChangXian': '长线',
    'PoMian': '泼面',
    'DaMian': '大面',
    'MoMian': '磨面',
    'ManFu': '满幅',
    'KuoMian': '阔面',
    'ChenMo': '沉墨',
    'DianJing': '点睛',
    'DianShi': '点石',
    'YiDian': '一点',
    'LuoMo': '落墨',
    'ShuSan': '疏散',
    'QianMiao': '浅描',
    'XiBi': '细笔',
    'DianYin': '点引',
    'MoDianV5': '墨点',
    'DianPoXuKong': '点破虚空',
    'HuiFeng': '回锋',
    'DianXianChengMian': '点线成面',
    'LiTouZhiBei': '力透纸背',
    'YiBiHua': '一笔画',
    'ZongHeng': '纵横',
    'XianTiao': '线条',
    'ZhiGuan': '直贯',
    'ChanSi': '缠丝',
    'YunJinChengFeng': '运斤成风',
    'BiFengYiZhuan': '笔锋一转',
    'YiXianTian': '一线天',
    'ChuanZhenYinXian': '穿针引线',
    'ChangQuZhiRu': '长驱直入',
    'LiDaoHuiLiu': '力道回流',
    'PoMoV5': '泼墨',
    'DaPoMo': '大泼墨',
    'ManZhiYunYan': '满纸云烟',
    'WanHeQianYan': '万壑千岩',
    'MoYunTianChengV5': '墨韵天成',
    'NongMoZhongCai': '浓墨重彩',
    'JuanZhou': '卷轴',
    'PoTianV5': '泼天',
    'LiYaQianJun': '力压千钧',
    'MoJin': '墨尽',
    'KuangCao': '狂草',
    'JieBi': '接笔',
    'XuZhi': '续纸',
    'WuShiWuZhong': '无始无终',
    'RunBi': '润笔',
    'DianJingZhiBi': '点睛之笔',
    'WanDianGuiYi': '万点归一',
    'ShuMiYouZhi': '疏密有致',
    'HaoLi': '毫厘',
    'DianShiChengJin': '点石成金',
    'MoShou': '墨守',
    'LiTouZhiBeiV5': '力透纸背',
    'TieHuaYinGou': '铁画银钩',
    'ZhongFeng': '中锋',
    'TieXian': '铁线',
    'XingYunLiuShui': '行云流水',
    'BiLaoMoXiu': '笔老墨秀',
    'QianJunYiBi': '千钧一笔',
    'PoTianAbility': '泼天',
    'WanShanHongBian': '万山红遍',
    'MoHai': '墨海',
    'ShanGaoShuiChang': '山高水长',
    'ChangJuan': '长卷',
    'LiTouWanXiang': '力透万象',
    'KaiTianPiDi': '开天辟地',
    'JingShuiLiuShen': '静水流深',
    'WanJieRuLinAncient': '万界如林',
    'WuMingZhiShi': '无名之始',
    'TaDeLaiChu': '她的来处',
    'HuoXuShiZhenDe': '或许是真的',
    'Mi': '谜',
}

TITLES_EN = {
    'DaJi': '打击',
    'FangYu': '防御',
    'QiBi': '起笔',
    'YunBi': '运笔',
    'ChengFu': '成幅',
    'QingDian': '轻点',
    'DianRan': '点染',
    'WeiMang': '微芒',
    'LuoDian': '落点',
    'ShuBi': '数笔',
    'DianZhui': '点缀',
    'DianPo': '点破',
    'HengXian': '横线',
    'ShuXian': '竖线',
    'GouXian': '勾线',
    'LianXian': '连线',
    'BiZhi': '笔直',
    'ZhiBi': '直笔',
    'ChangXian': '长线',
    'PoMian': '泼面',
    'DaMian': '大面',
    'MoMian': '磨面',
    'ManFu': '满幅',
    'KuoMian': '阔面',
    'ChenMo': '沉墨',
    'DianJing': '点睛',
    'DianShi': '点石',
    'YiDian': '一点',
    'LuoMo': '落墨',
    'ShuSan': '疏散',
    'QianMiao': '浅描',
    'XiBi': '细笔',
    'DianYin': '点引',
    'MoDianV5': '墨点',
    'DianPoXuKong': '点破虚空',
    'HuiFeng': '回锋',
    'DianXianChengMian': '点线成面',
    'LiTouZhiBei': '力透纸背',
    'YiBiHua': '一笔画',
    'ZongHeng': '纵横',
    'XianTiao': '线条',
    'ZhiGuan': '直贯',
    'ChanSi': '缠丝',
    'YunJinChengFeng': '运斤成风',
    'BiFengYiZhuan': '笔锋一转',
    'YiXianTian': '一线天',
    'ChuanZhenYinXian': '穿针引线',
    'ChangQuZhiRu': '长驱直入',
    'LiDaoHuiLiu': '力道回流',
    'PoMoV5': '泼墨',
    'DaPoMo': '大泼墨',
    'ManZhiYunYan': '满纸云烟',
    'WanHeQianYan': '万壑千岩',
    'MoYunTianChengV5': '墨韵天成',
    'NongMoZhongCai': '浓墨重彩',
    'JuanZhou': '卷轴',
    'PoTianV5': '泼天',
    'LiYaQianJun': '力压千钧',
    'MoJin': '墨尽',
    'KuangCao': '狂草',
    'JieBi': '接笔',
    'XuZhi': '续纸',
    'WuShiWuZhong': '无始无终',
    'RunBi': '润笔',
    'DianJingZhiBi': '点睛之笔',
    'WanDianGuiYi': '万点归一',
    'ShuMiYouZhi': '疏密有致',
    'HaoLi': '毫厘',
    'DianShiChengJin': '点石成金',
    'MoShou': '墨守',
    'LiTouZhiBeiV5': '力透纸背',
    'TieHuaYinGou': '铁画银钩',
    'ZhongFeng': '中锋',
    'TieXian': '铁线',
    'XingYunLiuShui': '行云流水',
    'BiLaoMoXiu': '笔老墨秀',
    'QianJunYiBi': '千钧一笔',
    'PoTianAbility': '泼天',
    'WanShanHongBian': '万山红遍',
    'MoHai': '墨海',
    'ShanGaoShuiChang': '山高水长',
    'ChangJuan': '长卷',
    'LiTouWanXiang': '力透万象',
    'KaiTianPiDi': '开天辟地',
    'JingShuiLiuShen': '静水流深',
    'WanJieRuLinAncient': '万界如林',
    'WuMingZhiShi': '无名之始',
    'TaDeLaiChu': '她的来处',
    'HuoXuShiZhenDe': '或许是真的',
    'Mi': '谜',
}
