# -*- coding: utf-8 -*-
r"""v0.3 卡牌文案（唯一真相源，供 gen_loc.py 覆盖）。

★ 与 `gen_cards89.py` 的规格**一一对应**：占位符名必须与卡牌声明的 DynamicVar 同名，
  否则 audit_placeholders.py 会报「未声明的占位符」。
  [gold] / [blue] / [pink] 是原版富文本标签；`\n` 是卡面换行。

约定（沿用 v0.1.2 起的排版规范）：
  · 数字与量词之间**不加空格**：{Damage:diff()}点伤害（原版 422:1）
  · 鬼气费用的动词用「**耗费**」
  · 条件句写在最前：「鬼气不高于 N 时才能打出。」
"""

ZH = {
# ---- Basic ----
'DaJi': '造成 {Damage:diff()}点伤害。',
'FangYu': '获得 {Block:diff()}点[gold]格挡[/gold]。',
'Hui': '耗费 1 点[gold]鬼气[/gold]。\n获得 {Block:diff()}点[gold]格挡[/gold]，抽 {Cards:diff()}张牌。',
# ---- Common ----
'SuMo': '造成 {Damage:diff()}点伤害，获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]。',
'YanMoInk': '获得 {Block:diff()}点[gold]格挡[/gold]，获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]。',
'MoDian': '获得 {Block:diff()}点[gold]格挡[/gold]，获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]。',
'LueDuo': '造成 {Damage:diff()}点伤害，获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]。',
'DianLongHuFa': '获得 {Block:diff()}点[gold]格挡[/gold]；下回合开始时再获得 {NextTurnBlock:diff()}点[gold]格挡[/gold]。',
'DanMo': '造成 {Damage:diff()}点伤害；你的[gold]鬼气[/gold]不高于 [blue]2[/blue] 时，额外造成 {ThinBonus:diff()}点伤害。',
'DanMiao': '获得 {Block:diff()}点[gold]格挡[/gold]；你的[gold]鬼气[/gold]不高于 [blue]2[/blue] 时，额外获得 {ThinBonus:diff()}点[gold]格挡[/gold]。',
'LiuBai': '抽 {Cards:diff()}张牌；你的[gold]鬼气[/gold]不高于 [blue]2[/blue] 时，再抽 [blue]1[/blue]张牌。',
'XiBi': '失去所有[gold]鬼气[/gold]。每失去 [blue]1[/blue]点，获得 {BlockPerQi:diff()}点[gold]格挡[/gold]。',
'TuiGui': '[gold]鬼气[/gold]为 [blue]0[/blue] 时才能打出。\\n造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次。',
'FengBi': '获得 {Block:diff()}点[gold]格挡[/gold]。本回合你无法获得[gold]鬼气[/gold]。',
'BanYan': '每回合结束时，若你的[gold]鬼气[/gold]在 [blue]3[/blue] 到 [blue]7[/blue] 之间，获得 {BlockPerTurn:diff()}点[gold]格挡[/gold]。',
'SuLian': '获得 {Block:diff()}点[gold]格挡[/gold]；你的[gold]鬼气[/gold]在 [blue]3[/blue] 到 [blue]7[/blue] 之间时，额外获得 {EvenBonus:diff()}点[gold]格挡[/gold]。',
'NongDanXiangSheng': '若你的[gold]鬼气[/gold]不低于 [blue]6[/blue]：失去 {QiSwing:diff()}点[gold]鬼气[/gold]并抽 {Cards:diff()}张牌；\\n否则获得 {QiSwing:diff()}点[gold]鬼气[/gold]并抽 [blue]1[/blue]张牌。',
'YunMo': '将你的[gold]鬼气[/gold]设为 {SetTo:diff()}。\\n抽 {Cards:diff()}张牌。',
'HuanQi': '将你的[gold]鬼气[/gold]变为 {Mirror:diff()} 减去当前值。\\n抽 {Cards:diff()}张牌。',
'BiMoQingXie': '耗费所有[gold]鬼气[/gold]。\\n对所有敌人造成 X+{BonusDamage:diff()} 点伤害。',
'DianXian': '耗费所有[gold]鬼气[/gold]。\\n造成 {Damage:diff()}点伤害，共 X 次。',
'QinShi': '耗费 1 点[gold]鬼气[/gold]。\n造成 {Damage:diff()}点伤害，给予 {Vulnerable:diff()}层[gold]易伤[/gold]。',
'ShenShiDuoShi': '耗费所有[gold]鬼气[/gold]。每 {QiPerEnergy:diff()}点鬼气，获得 [blue]1[/blue]点[gold]能量[/gold]。\\n[gold]消耗[/gold]。',
'XiaoHuo': '耗费 1 点[gold]鬼气[/gold]。\n获得 {Block:diff()}点[gold]格挡[/gold]。',
'ChiXuQinRao': '耗费 1 点[gold]鬼气[/gold]。\n给予 {Vulnerable:diff()}层[gold]易伤[/gold]与 {Weak:diff()}层[gold]虚弱[/gold]，造成 {Damage:diff()}点伤害。',
'HuiHao': '造成 {Damage:diff()}点伤害。你的[gold]鬼气[/gold]每有 [blue]5[/blue]点，此伤害 +[blue]2[/blue]。',
'DaMengYiChang': '获得 {Block:diff()}点[gold]格挡[/gold]；下回合开始时抽 {Cards:diff()}张牌。',
'GuangMingQieGe': '敌人失去 {StrengthLoss:diff()}点[gold]力量[/gold]。\\n[gold]消耗[/gold]。',
# ---- Uncommon ----
'PoMo': '造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次，获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]。',
'MoLong': '造成 {Damage:diff()}点伤害；你的[gold]鬼气[/gold]不低于 [blue]10[/blue] 时，额外造成 {HighBonus:diff()}点伤害。',
'HuiHuaFenGe': '获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]，造成 {Damage:diff()}点伤害。',
'DuZiShengJi': '获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]，抽 [blue]1[/blue]张牌。\\n[gold]消耗[/gold]。',
'NingMo': '获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]；下回合开始时再获得 {NextTurn:diff()}点[gold]鬼气[/gold]。',
'GuiYingSenSen': '每回合最多触发 {Threshold:diff()} 次：你造成伤害时，获得 [blue]1[/blue]点[gold]鬼气[/gold]。',
'NongMoZhongCai': '每回合最多获得 {MaxBlockPerTurn:diff()}点[gold]格挡[/gold]：你获得[gold]鬼气[/gold]时，获得等量的[gold]格挡[/gold]。',
'YanMoXiaBi': '[gold]鬼气[/gold]不低于 [blue]4[/blue] 时才能打出。\\n造成 {Damage:diff()}点伤害。',
'MoHaiFanTeng': '造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次；你的[gold]鬼气[/gold]不低于 [blue]10[/blue] 时，改为 3 次。',
'HuaShen': '每回合最多触发 {Cap:diff()} 次：你消耗[gold]鬼气[/gold]时，抽 [blue]1[/blue]张牌并获得 [blue]1[/blue]点[gold]能量[/gold]。',
'LiGuiFuSu': '你接下来获得的[gold]能量[/gold]全部转为等量的[gold]鬼气[/gold]。\\n每回合开始时额外获得 {GhostQiPerTurn:diff()}点[gold]鬼气[/gold]。',
'KuFeng': '[gold]鬼气[/gold]不高于 [blue]3[/blue] 时才能打出。\\n造成 {Damage:diff()}点伤害。',
'GanBi': '造成 {Damage:diff()}点伤害，失去 [blue]3[/blue]点[gold]鬼气[/gold]；若因此[gold]鬼气[/gold]不高于 [blue]2[/blue]，额外造成 {ThinBonus:diff()}点伤害。',
'TiaoDeng': '造成 {Damage:diff()}点伤害；你的[gold]鬼气[/gold]不高于 [blue]2[/blue] 时，抽 {Cards:diff()}张牌。',
'LianFeng': '[gold]鬼气[/gold]不高于 [blue]2[/blue] 时才能打出。\\n获得 {Block:diff()}点[gold]格挡[/gold]，抽 {Cards:diff()}张牌。',
'ChengXin': '失去 {GhostQiLoss:diff()}点[gold]鬼气[/gold]，抽 {Cards:diff()}张牌。',
'XiaBi': '造成 {Damage:diff()}点伤害；下回合开始时获得 {NextTurn:diff()}点[gold]鬼气[/gold]。',
'CangFeng': '耗费 1 点[gold]鬼气[/gold]。\n抽 {Cards:diff()}张牌。',
'HeiAnBiZhang': '耗费 1 点[gold]鬼气[/gold]。\n获得 {Block:diff()}点[gold]格挡[/gold]。',
'YaZhiYuWang': '耗费 1 点[gold]鬼气[/gold]。\n下回合开始时获得 {NextTurn:diff()}点[gold]鬼气[/gold]。',
'BaoWu': '每回合开始时，若你的[gold]鬼气[/gold]不高于 [blue]2[/blue]，获得 {EnergyPerTurn:diff()}点[gold]能量[/gold]。',
'CengCengQinShi': '获得 {GhostQiGain:diff()}点[gold]鬼气[/gold]，抽 {Cards:diff()}张牌。',
'PoYan': '失去所有[gold]鬼气[/gold]，每 {QiPerEnergy:diff()}点获得 [blue]1[/blue]点[gold]能量[/gold]；抽 [blue]1[/blue]张牌。\\n[gold]消耗[/gold]。',
'ChengMo': '失去所有[gold]鬼气[/gold]，每 {QiPerCard:diff()}点抽 [blue]1[/blue]张牌。\\n[gold]消耗[/gold]。',
'WoRuoWeiGui': '下回合获得的[gold]能量[/gold]全部转为[gold]鬼气[/gold]。\\n下回合抽 {Cards:diff()}张牌。\\n[gold]消耗[/gold]。',
'WoRuoWeiShen': '下回合获得的[gold]鬼气[/gold]全部转为[gold]能量[/gold]。\\n下回合可以免费打出 {FreeCards:diff()}张牌。\\n[gold]消耗[/gold]。',
'TunShi': '每回合最多触发 [blue]2[/blue] 次：你获得[gold]鬼气[/gold]时，抽 [blue]1[/blue]张牌。',
'NongDanYouXin': '每回合最多触发 {MaxTriggersPerTurn:diff()} 次：你获得[gold]鬼气[/gold]时获得 [blue]3[/blue]点[gold]格挡[/gold]；失去[gold]鬼气[/gold]时抽 [blue]1[/blue]张牌。',
'YinYangGeHunXiao': '耗费 2 点[gold]鬼气[/gold]。\n打出攻击牌时抽 {DrawPerAttack:diff()}张牌；打出技能牌时获得 [blue]1[/blue]点[gold]格挡[/gold]。',
'JingShui': '获得 {Block:diff()}点[gold]格挡[/gold]。本回合你无法获得[gold]鬼气[/gold]。',
'GuiQiXunHuan': '每回合结束时：若你的[gold]鬼气[/gold]不低于 [blue]8[/blue]，失去 {AmountPerTurn:diff()}点；若不高于 [blue]2[/blue]，获得 {AmountPerTurn:diff()}点。',
'ShengWenZi': '给予 {Vulnerable:diff()}层[gold]易伤[/gold]与 {Weak:diff()}层[gold]虚弱[/gold]，造成 {Damage:diff()}点伤害。',
'DuanXu': '失去 {GhostQiLoss:diff()}点[gold]鬼气[/gold]。造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次。',
'YinSen': '给予 {Vulnerable:diff()}层[gold]易伤[/gold]。造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次。',
'PiaoMiaoJianJue': '耗费 2 点[gold]鬼气[/gold]。\n造成 {Damage:diff()}点伤害，随机获得一把剑。\\n[gold]消耗[/gold]。',
'ZanBiFengMang': '获得 [blue]3[/blue]点[gold]格挡[/gold]。下回合开始时获得 {EnergyNextTurn:diff()}点[gold]能量[/gold]与 {GhostQiNextTurn:diff()}点[gold]鬼气[/gold]。',
'PingXingShiJie': '弃掉任意张手牌（X）。\\n抽 X+{BonusDraw:diff()} 张牌。',
# ---- Rare ----
'YiHuaKaiTian': '造成 {Damage:diff()}点伤害；你的[gold]鬼气[/gold]不低于 [blue]12[/blue] 时，额外造成 {HighBonus:diff()}点伤害。\\n[gold]消耗[/gold]。',
'YouYouDianLong': '[gold]鬼气[/gold]不低于 [blue]10[/blue] 时才能打出。\\n失去所有[gold]鬼气[/gold]。每 {QiPerHit:diff()}点鬼气，造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次。',
'GuiYu': '每回合开始时抽 [blue]2[/blue]张牌。',
'GuangMingYuYan': '每回合最多触发 {MaxTriggersPerTurn:diff()} 次：你失去生命时，每失去 [blue]2[/blue]点生命获得 [blue]1[/blue]点[gold]鬼气[/gold]。',
'AoMan': '[gold]鬼气[/gold]不低于 [blue]14[/blue] 时才能打出。\\n抽 {Cards:diff()}张牌。\\n[gold]消耗[/gold]。',
'SuXinYiJian': '[gold]鬼气[/gold]为 [blue]0[/blue] 时才能打出。\\n造成 {Damage:diff()}点伤害，抽 {Cards:diff()}张牌。\\n[gold]消耗[/gold]。',
'XiJinQianHua': '失去所有[gold]鬼气[/gold]。造成 {Damage:diff()}点伤害；每失去 {QiPerBonus:diff()}点[gold]鬼气[/gold]，此伤害 +{BonusPer:diff()}。',
'ShuYing': '获得等于当前[gold]鬼气[/gold] {PerQi:diff()} 倍的[gold]格挡[/gold]（最多 {Cap:diff()} 点）。',
'KongMing': '[gold]鬼气[/gold]不高于 [blue]2[/blue] 时才能打出。\\n抽 {Cards:diff()}张牌，获得 [blue]2[/blue]点[gold]能量[/gold]。\\n[gold]消耗[/gold]。',
'MangXinJian': '敌人失去 {StrengthLoss:diff()}点[gold]力量[/gold]。\\n[gold]消耗[/gold]。',
'YangGuangPuZhao': '[gold]鬼气[/gold]为 [blue]0[/blue] 时才能打出。\\n对所有敌人造成 {Damage:diff()}点伤害，获得 {Block:diff()}点[gold]格挡[/gold]。\\n[gold]消耗[/gold]。',
'XianMian': '耗费所有[gold]鬼气[/gold]。\\n对所有敌人造成 {Damage:diff()}点伤害，每耗费 [blue]1[/blue]点[gold]鬼气[/gold]此伤害 +{BonusPerQi:diff()}。',
'Jian': '每回合开始时获得 {SwordsPerTurn:diff()}把剑。抽 {Cards:diff()}张牌。\\n[gold]消耗[/gold]。',
'WoBuWanLe': '耗费所有[gold]鬼气[/gold]。接下来 X+{BonusFree:diff()} 张牌可以免费打出。\\n[gold]消耗[/gold]。',
'AoJiao': '抽 {Cards:diff()}张牌，获得这些牌面板伤害合计的[gold]格挡[/gold]。\n[gold]消耗[/gold]。',
'GuiYi': '将你的[gold]鬼气[/gold]设为 {SetTo:diff()}，获得 {Block:diff()}点[gold]格挡[/gold]。\\n[gold]消耗[/gold]。',
'MoYunTianCheng': '每回合结束时，若你的[gold]鬼气[/gold]在 [blue]3[/blue] 到 [blue]7[/blue] 之间，抽 {Cards:diff()}张牌并获得 {EnergyPerTurn:diff()}点[gold]能量[/gold]。',
'DianLongXingTai': '每回合开始时获得 [blue]3[/blue]点[gold]临时力量[/gold]和 [blue]10[/blue]点[gold]活力[/gold]。',
'ShenShengBaoZou': '本回合你的攻击牌伤害翻倍；每打出 {AttacksPerGhostQi:diff()}张攻击牌，额外消耗 [blue]1[/blue]点[gold]鬼气[/gold]（鬼气不足时该牌无法打出）。',
'ShiTong': '[gold]鬼气[/gold]在 [blue]3[/blue] 到 [blue]7[/blue] 之间时才能打出。\n本回合每打出一张牌，获得 [blue]1[/blue]点[gold]鬼气[/gold]。',
'YouRanGuiHuo': '给予 {Vulnerable:diff()}层[gold]易伤[/gold]。造成 {Damage:diff()}点伤害，共 {Repeat:diff()} 次；你的[gold]鬼气[/gold]每有 {QiPerExtraHit:diff()}点，次数 +[blue]1[/blue]。',
# ---- Ancient / Event / Token ----
'MoRanJiangShan': '耗费所有[gold]鬼气[/gold]。本回合获得 X+{BonusStat:diff()} 点[gold]临时力量[/gold]和 X+{BonusStat:diff()} 点[gold]临时敏捷[/gold]（X 为你耗费的鬼气）。\\n[gold]保留[/gold]。',
'GuiQiSenSen': '你接下来的回合不再获得[gold]能量[/gold]，改为获得同等数值的[gold]鬼气[/gold]。\\n每回合开始时额外抽 {Cards:diff()}张牌。',
'YinSenSen': '造成 {Damage:diff()}点伤害。\\n[gold]消耗[/gold]。',
}

EN = {
# ---- Basic ----
'DaJi': 'Deal {Damage:diff()} damage.',
'FangYu': 'Gain {Block:diff()} [gold]Block[/gold].',
'Hui': 'Spend 1 [gold]Ghost Qi[/gold].\nGain {Block:diff()} [gold]Block[/gold]. Draw {Cards:diff()} card(s).',
# ---- Common ----
'SuMo': 'Deal {Damage:diff()} damage. Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold].',
'YanMoInk': 'Gain {Block:diff()} [gold]Block[/gold]. Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold].',
'MoDian': 'Gain {Block:diff()} [gold]Block[/gold]. Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold].',
'LueDuo': 'Deal {Damage:diff()} damage. Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold].',
'DianLongHuFa': 'Gain {Block:diff()} [gold]Block[/gold]. Next turn, gain {NextTurnBlock:diff()} more [gold]Block[/gold].',
'DanMo': 'Deal {Damage:diff()} damage. If your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less, deal {ThinBonus:diff()} more.',
'DanMiao': 'Gain {Block:diff()} [gold]Block[/gold]. If your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less, gain {ThinBonus:diff()} more.',
'LiuBai': 'Draw {Cards:diff()} card(s). If your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less, draw [blue]1[/blue] more.',
'XiBi': 'Lose all [gold]Ghost Qi[/gold]. For each [blue]1[/blue] lost, gain {BlockPerQi:diff()} [gold]Block[/gold].',
'TuiGui': 'Can only be played if you have [blue]0[/blue] [gold]Ghost Qi[/gold].\\nDeal {Damage:diff()} damage {Repeat:diff()} times.',
'FengBi': 'Gain {Block:diff()} [gold]Block[/gold]. You cannot gain [gold]Ghost Qi[/gold] this turn.',
'BanYan': 'At the end of each turn, if your [gold]Ghost Qi[/gold] is between [blue]3[/blue] and [blue]7[/blue], gain {BlockPerTurn:diff()} [gold]Block[/gold].',
'SuLian': 'Gain {Block:diff()} [gold]Block[/gold]. If your [gold]Ghost Qi[/gold] is between [blue]3[/blue] and [blue]7[/blue], gain {EvenBonus:diff()} more.',
'NongDanXiangSheng': 'If your [gold]Ghost Qi[/gold] is [blue]6[/blue] or more: lose {QiSwing:diff()} [gold]Ghost Qi[/gold] and draw {Cards:diff()} card(s).\\nOtherwise: gain {QiSwing:diff()} [gold]Ghost Qi[/gold] and draw [blue]1[/blue] card.',
'YunMo': 'Set your [gold]Ghost Qi[/gold] to {SetTo:diff()}.\\nDraw {Cards:diff()} card(s).',
'HuanQi': 'Change your [gold]Ghost Qi[/gold] to {Mirror:diff()} minus its current value.\\nDraw {Cards:diff()} card(s).',
'BiMoQingXie': 'Spend all [gold]Ghost Qi[/gold].\\nDeal X+{BonusDamage:diff()} damage to ALL enemies.',
'DianXian': 'Spend all [gold]Ghost Qi[/gold].\\nDeal {Damage:diff()} damage X times.',
'QinShi': 'Spend 1 [gold]Ghost Qi[/gold].\nDeal {Damage:diff()} damage. Apply {Vulnerable:diff()} [gold]Vulnerable[/gold].',
'ShenShiDuoShi': 'Spend all [gold]Ghost Qi[/gold]. For every {QiPerEnergy:diff()} Ghost Qi, gain [blue]1[/blue] [gold]Energy[/gold].\\n[gold]Exhaust[/gold].',
'XiaoHuo': 'Spend 1 [gold]Ghost Qi[/gold].\nGain {Block:diff()} [gold]Block[/gold].',
'ChiXuQinRao': 'Spend 1 [gold]Ghost Qi[/gold].\nApply {Vulnerable:diff()} [gold]Vulnerable[/gold] and {Weak:diff()} [gold]Weak[/gold]. Deal {Damage:diff()} damage.',
'HuiHao': 'Deal {Damage:diff()} damage. For every [blue]5[/blue] [gold]Ghost Qi[/gold] you have, this deals [blue]2[/blue] more.',
'DaMengYiChang': 'Gain {Block:diff()} [gold]Block[/gold]. Next turn, draw {Cards:diff()} card(s).',
'GuangMingQieGe': 'Enemy loses {StrengthLoss:diff()} [gold]Strength[/gold].\\n[gold]Exhaust[/gold].',
# ---- Uncommon ----
'PoMo': 'Deal {Damage:diff()} damage {Repeat:diff()} times. Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold].',
'MoLong': 'Deal {Damage:diff()} damage. If your [gold]Ghost Qi[/gold] is [blue]10[/blue] or more, deal {HighBonus:diff()} more.',
'HuiHuaFenGe': 'Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold]. Deal {Damage:diff()} damage.',
'DuZiShengJi': 'Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold]. Draw [blue]1[/blue] card.\\n[gold]Exhaust[/gold].',
'NingMo': 'Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold]. Next turn, gain {NextTurn:diff()} more.',
'GuiYingSenSen': 'Up to {Threshold:diff()} times per turn: whenever you deal damage, gain [blue]1[/blue] [gold]Ghost Qi[/gold].',
'NongMoZhongCai': 'Up to {MaxBlockPerTurn:diff()} [gold]Block[/gold] per turn: whenever you gain [gold]Ghost Qi[/gold], gain that much [gold]Block[/gold].',
'YanMoXiaBi': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]4[/blue] or more.\\nDeal {Damage:diff()} damage.',
'MoHaiFanTeng': 'Deal {Damage:diff()} damage {Repeat:diff()} times. If your [gold]Ghost Qi[/gold] is [blue]10[/blue] or more, 3 times instead.',
'HuaShen': 'Up to {Cap:diff()} times per turn: whenever you spend [gold]Ghost Qi[/gold], draw [blue]1[/blue] card and gain [blue]1[/blue] [gold]Energy[/gold].',
'LiGuiFuSu': 'All [gold]Energy[/gold] you would gain is converted into [gold]Ghost Qi[/gold].\\nAt the start of each turn, gain {GhostQiPerTurn:diff()} extra [gold]Ghost Qi[/gold].',
'KuFeng': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]3[/blue] or less.\\nDeal {Damage:diff()} damage.',
'GanBi': 'Deal {Damage:diff()} damage. Lose [blue]3[/blue] [gold]Ghost Qi[/gold]. If your [gold]Ghost Qi[/gold] is now [blue]2[/blue] or less, deal {ThinBonus:diff()} more.',
'TiaoDeng': 'Deal {Damage:diff()} damage. If your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less, draw {Cards:diff()} card(s).',
'LianFeng': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less.\\nGain {Block:diff()} [gold]Block[/gold]. Draw {Cards:diff()} card(s).',
'ChengXin': 'Lose {GhostQiLoss:diff()} [gold]Ghost Qi[/gold]. Draw {Cards:diff()} card(s).',
'XiaBi': 'Deal {Damage:diff()} damage. Next turn, gain {NextTurn:diff()} [gold]Ghost Qi[/gold].',
'CangFeng': 'Spend 1 [gold]Ghost Qi[/gold].\nDraw {Cards:diff()} card(s).',
'HeiAnBiZhang': 'Spend 1 [gold]Ghost Qi[/gold].\nGain {Block:diff()} [gold]Block[/gold].',
'YaZhiYuWang': 'Spend 1 [gold]Ghost Qi[/gold].\nNext turn, gain {NextTurn:diff()} [gold]Ghost Qi[/gold].',
'BaoWu': 'At the start of each turn, if your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less, gain {EnergyPerTurn:diff()} [gold]Energy[/gold].',
'CengCengQinShi': 'Gain {GhostQiGain:diff()} [gold]Ghost Qi[/gold]. Draw {Cards:diff()} card(s).',
'PoYan': 'Lose all [gold]Ghost Qi[/gold]; for every {QiPerEnergy:diff()} lost, gain [blue]1[/blue] [gold]Energy[/gold]. Draw [blue]1[/blue] card.\\n[gold]Exhaust[/gold].',
'ChengMo': 'Lose all [gold]Ghost Qi[/gold]; for every {QiPerCard:diff()} lost, draw [blue]1[/blue] card.\\n[gold]Exhaust[/gold].',
'WoRuoWeiGui': 'Next turn, all [gold]Energy[/gold] you would gain is converted into [gold]Ghost Qi[/gold].\\nNext turn, draw {Cards:diff()} card(s).\\n[gold]Exhaust[/gold].',
'WoRuoWeiShen': 'Next turn, all [gold]Ghost Qi[/gold] you would gain is converted into [gold]Energy[/gold].\\nNext turn, play {FreeCards:diff()} card(s) for free.\\n[gold]Exhaust[/gold].',
'TunShi': 'Up to [blue]2[/blue] times per turn: whenever you gain [gold]Ghost Qi[/gold], draw [blue]1[/blue] card.',
'NongDanYouXin': 'Up to {MaxTriggersPerTurn:diff()} times per turn: when you gain [gold]Ghost Qi[/gold], gain [blue]3[/blue] [gold]Block[/gold]; when you lose [gold]Ghost Qi[/gold], draw [blue]1[/blue] card.',
'YinYangGeHunXiao': 'Spend 2 [gold]Ghost Qi[/gold].\nWhenever you play an Attack, draw {DrawPerAttack:diff()} card(s); whenever you play a Skill, gain [blue]1[/blue] [gold]Block[/gold].',
'JingShui': 'Gain {Block:diff()} [gold]Block[/gold]. You cannot gain [gold]Ghost Qi[/gold] this turn.',
'GuiQiXunHuan': 'At the end of each turn: if your [gold]Ghost Qi[/gold] is [blue]8[/blue] or more, lose {AmountPerTurn:diff()}; if it is [blue]2[/blue] or less, gain {AmountPerTurn:diff()}.',
'ShengWenZi': 'Apply {Vulnerable:diff()} [gold]Vulnerable[/gold] and {Weak:diff()} [gold]Weak[/gold]. Deal {Damage:diff()} damage.',
'DuanXu': 'Lose {GhostQiLoss:diff()} [gold]Ghost Qi[/gold]. Deal {Damage:diff()} damage {Repeat:diff()} times.',
'YinSen': 'Apply {Vulnerable:diff()} [gold]Vulnerable[/gold]. Deal {Damage:diff()} damage {Repeat:diff()} times.',
'PiaoMiaoJianJue': 'Spend 2 [gold]Ghost Qi[/gold].\nDeal {Damage:diff()} damage. Gain a random sword.\\n[gold]Exhaust[/gold].',
'ZanBiFengMang': 'Gain [blue]3[/blue] [gold]Block[/gold]. Next turn, gain {EnergyNextTurn:diff()} [gold]Energy[/gold] and {GhostQiNextTurn:diff()} [gold]Ghost Qi[/gold].',
'PingXingShiJie': 'Discard any number of cards (X).\\nDraw X+{BonusDraw:diff()} card(s).',
# ---- Rare ----
'YiHuaKaiTian': 'Deal {Damage:diff()} damage. If your [gold]Ghost Qi[/gold] is [blue]12[/blue] or more, deal {HighBonus:diff()} more.\\n[gold]Exhaust[/gold].',
'YouYouDianLong': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]10[/blue] or more.\\nLose all [gold]Ghost Qi[/gold]; for every {QiPerHit:diff()} lost, deal {Damage:diff()} damage. {Repeat:diff()} times.',
'GuiYu': 'At the start of each turn, draw [blue]2[/blue] card(s).',
'GuangMingYuYan': 'Up to {MaxTriggersPerTurn:diff()} times per turn: whenever you lose HP, gain [blue]1[/blue] [gold]Ghost Qi[/gold] for every [blue]2[/blue] HP lost.',
'AoMan': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]14[/blue] or more.\\nDraw {Cards:diff()} card(s).\\n[gold]Exhaust[/gold].',
'SuXinYiJian': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]0[/blue].\\nDeal {Damage:diff()} damage. Draw {Cards:diff()} card(s).\\n[gold]Exhaust[/gold].',
'XiJinQianHua': 'Lose all [gold]Ghost Qi[/gold]. Deal {Damage:diff()} damage; for every {QiPerBonus:diff()} [gold]Ghost Qi[/gold] lost, this deals +{BonusPer:diff()}.',
'ShuYing': 'Gain [gold]Block[/gold] equal to {PerQi:diff()} times your [gold]Ghost Qi[/gold] (max {Cap:diff()}).',
'KongMing': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]2[/blue] or less.\\nDraw {Cards:diff()} card(s). Gain [blue]2[/blue] [gold]Energy[/gold].\\n[gold]Exhaust[/gold].',
'MangXinJian': 'Enemy loses {StrengthLoss:diff()} [gold]Strength[/gold].\\n[gold]Exhaust[/gold].',
'YangGuangPuZhao': 'Can only be played if your [gold]Ghost Qi[/gold] is [blue]0[/blue].\\nDeal {Damage:diff()} damage to ALL enemies. Gain {Block:diff()} [gold]Block[/gold].\\n[gold]Exhaust[/gold].',
'XianMian': 'Spend all [gold]Ghost Qi[/gold].\\nDeal {Damage:diff()} damage to ALL enemies, plus +{BonusPerQi:diff()} for every [blue]1[/blue] [gold]Ghost Qi[/gold] spent.',
'Jian': 'At the start of each turn, gain {SwordsPerTurn:diff()} sword(s). Draw {Cards:diff()} card(s).\\n[gold]Exhaust[/gold].',
'WoBuWanLe': 'Spend all [gold]Ghost Qi[/gold]. The next X+{BonusFree:diff()} card(s) can be played for free.\\n[gold]Exhaust[/gold].',
'AoJiao': 'Draw {Cards:diff()} card(s). Gain [gold]Block[/gold] equal to the total damage of the Attacks drawn.\n[gold]Exhaust[/gold].',
'GuiYi': 'Set your [gold]Ghost Qi[/gold] to {SetTo:diff()}. Gain {Block:diff()} [gold]Block[/gold].\\n[gold]Exhaust[/gold].',
'MoYunTianCheng': 'At the end of each turn, if your [gold]Ghost Qi[/gold] is between [blue]3[/blue] and [blue]7[/blue], draw {Cards:diff()} card(s) and gain {EnergyPerTurn:diff()} [gold]Energy[/gold].',
'DianLongXingTai': 'At the start of each turn, gain [blue]3[/blue] [gold]Temporary Strength[/gold] and [blue]10[/blue] [gold]Vigor[/gold].',
'ShenShengBaoZou': 'Your Attacks deal double damage this turn; for every {AttacksPerGhostQi:diff()} Attack(s) played, spend [blue]1[/blue] extra [gold]Ghost Qi[/gold] (the Attack cannot be played if you have none).',
'ShiTong': 'Can only be played if your [gold]Ghost Qi[/gold] is between [blue]3[/blue] and [blue]7[/blue].\nThis turn, whenever you play a card, gain [blue]1[/blue] [gold]Ghost Qi[/gold].',
'YouRanGuiHuo': 'Apply {Vulnerable:diff()} [gold]Vulnerable[/gold]. Deal {Damage:diff()} damage {Repeat:diff()} times; for every {QiPerExtraHit:diff()} [gold]Ghost Qi[/gold] you have, +[blue]1[/blue] more time.',
# ---- Ancient / Event / Token ----
'MoRanJiangShan': 'Spend all [gold]Ghost Qi[/gold]. Gain X+{BonusStat:diff()} [gold]Temporary Strength[/gold] and X+{BonusStat:diff()} [gold]Temporary Dexterity[/gold] this turn, where X is the Ghost Qi spent.\\n[gold]Retain[/gold].',
'GuiQiSenSen': 'On future turns you no longer gain [gold]Energy[/gold]; instead you gain that much [gold]Ghost Qi[/gold].\\nAt the start of each turn, draw {Cards:diff()} extra card.',
'YinSenSen': 'Deal {Damage:diff()} damage.\\n[gold]Exhaust[/gold].',
}
