# -*- coding: utf-8 -*-
r"""v0.5 卡牌文案（自动生成，可用 gen_cards_v05.py 的 doc 重跑同步）。"""

ZH = {
    'DaJi': '造成 {Damage:diff()} 点伤害。',
    'FangYu': '获得 {Block:diff()} 点格挡。',
    'QiBi': '点 —— 造成 {Damage:diff()} 点伤害。 若你本回合已打出过「点」牌，此牌伤害改为 14 点。',
    'YunBi': '线 —— 获得 {Block:diff()} 点格挡。 打出后本回合获得 1 点临时力量与 1 点临时敏捷，并抽 1 张牌（千钧一线）。',
    'ChengFu': '面 —— 造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆（去年今日此门中）。',
    'QingDian': '点 —— 造成 {Damage:diff()} 点伤害。抽 {Cards:diff()} 张牌。',
    'DianRan': '点 —— 获得 {Block:diff()} 点格挡。抽 {Cards:diff()} 张牌。',
    'WeiMang': '点 —— 0 费：造成 {Damage:diff()} 点伤害。',
    'LuoDian': '点 —— 0 费：抽 {Cards:diff()} 张牌。',
    'ShuBi': '点 —— 抽 {Cards:diff()} 张牌。',
    'DianZhui': '点 —— 造成 {Damage:diff()} 点伤害。抽 {Cards:diff()} 张牌。',
    'DianPo': '点 —— 敌人失去 {Cards:diff()} 点力量。抽 {StrengthLoss:diff()} 张牌。',
    'HengXian': '线 —— 造成 {Damage:diff()} 点伤害，给予 {Weak:diff()} 层虚弱。 （千钧一线：另获 1 临时力量/敏捷 + 抽 1 张）。',
    'ShuXian': '线 —— 获得 {Block:diff()} 点格挡。抽 {Cards:diff()} 张牌。',
    'GouXian': '线 —— 抽 {Cards:diff()} 张牌。 （千钧一线：另获 1 临时力量/敏捷 + 抽 1 张）。',
    'LianXian': '线 —— 造成 {Damage:diff()} 点伤害，获得 {Block:diff()} 点格挡。 （千钧一线：另获 1 临时力量/敏捷 + 抽 1 张）。',
    'BiZhi': '线 —— 获得 {Block:diff()} 点格挡。抽 {Cards:diff()} 张牌。',
    'ZhiBi': '线 —— 造成 {Damage:diff()} 点伤害，给予 {Vulnerable:diff()} 层易伤。',
    'ChangXian': '线 —— 造成 {Damage:diff()} 点伤害。抽 {Cards:diff()} 张牌。 （千钧一线：另获 1 临时力量/敏捷 + 抽 1 张）。',
    'PoMian': '面 —— 造成 {Damage:diff()} 点伤害，给予 {Vulnerable:diff()} 层易伤。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'DaMian': '面 —— 获得 {Block:diff()} 点格挡。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'MoMian': '面 —— 抽 {Cards:diff()} 张牌，获得 1 点能量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'ManFu': '面 —— 获得 {Damage:diff()} 点格挡，造成 12 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'KuoMian': '面 —— 对所有敌人造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'ChenMo': '面 —— 本回合获得 {Cards:diff()} 点临时力量，抽 2 张牌。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'DianJing': '点 —— 0 费：抽 {Cards:diff()} 张牌。',
    'DianShi': '点 —— 获得 {Cards:diff()} 点能量。抽 {Energy:diff()} 张牌。',
    'YiDian': '点 —— 0 费：造成 {Damage:diff()} 点伤害，共 {Repeat:diff()} 次。',
    'LuoMo': '点 —— 获得 {Block:diff()} 点格挡。抽 {Cards:diff()} 张牌。',
    'ShuSan': '点 —— 抽 {Cards:diff()} 张牌。',
    'QianMiao': '点 —— 造成 {Damage:diff()} 点伤害，给予 {Vulnerable:diff()} 层易伤。',
    'XiBi': '点 —— 0 费：造成 {Damage:diff()} 点伤害。',
    'DianYin': '点 —— 抽 {Cards:diff()} 张牌。若你本回合已打出 3 张以上点牌，额外获得 {Energy:diff()} 点能量。',
    'MoDianV5': '点 —— 造成 {Damage:diff()} 点伤害。获得等同于本回合已打出点牌数 ×2 的格挡。',
    'DianPoXuKong': '点 —— 造成 {Damage:diff()} 点伤害。',
    'HuiFeng': '点 —— 0 费：失去 {BloodCost:diff()} 点生命，造成 {Damage:diff()} 点伤害。',
    'DianXianChengMian': '线 —— 抽 {Cards:diff()} 张牌。若本回合已打出 2 张以上点牌，额外获得 {Energy:diff()} 点能量。',
    'LiTouZhiBei': '线 —— 获得 {Block:diff()} 点格挡，额外获得 2 点临时力量。 （千钧一线：另 +1 临时力/敏 + 抽 1 张）。',
    'YiBiHua': '线 —— 造成 {Damage:diff()} 点伤害，获得 {Block:diff()} 点格挡。',
    'ZongHeng': '线 —— 获得 2 点临时力量与 2 点临时敏捷。',
    'XianTiao': '线 —— 造成 {Damage:diff()} 点伤害，抽 {Cards:diff()} 张牌。 （千钧一线：另 +1 临时力/敏 + 抽 1 张）。',
    'ZhiGuan': '线 —— 造成 {Damage:diff()} 点伤害。若本回合已打出 2 张以上线牌，伤害翻倍。',
    'ChanSi': '线 —— 获得 {Block:diff()} 点格挡，额外获得 2 点临时敏捷。',
    'YunJinChengFeng': '线 —— 抽 {Cards:diff()} 张牌。 （千钧一线：另 +1 临时力/敏 + 抽 1 张）。',
    'BiFengYiZhuan': '线 —— 获得 3 点临时力量。',
    'YiXianTian': '线 —— 需本回合已打出 3 张以上线牌才能打出。 造成 {Damage:diff()} 点伤害。',
    'ChuanZhenYinXian': '线 —— 造成 {Damage:diff()} 点伤害。你每打出过 1 张线牌，此伤害 +2。',
    'ChangQuZhiRu': '线 —— 造成 {Damage:diff()} 点伤害，额外获得 3 点临时力量。',
    'LiDaoHuiLiu': '线 —— 获得 {Cards:diff()} 点临时力量，抽 2 张牌。',
    'PoMoV5': '面 —— 对所有敌人造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'DaPoMo': '面 —— 对所有敌人造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'ManZhiYunYan': '面 —— 获得 {Block:diff()} 点格挡。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'WanHeQianYan': '面 —— 获得 {Block:diff()} 点格挡。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'MoYunTianChengV5': '面 —— 抽 {Cards:diff()} 张牌，获得 2 点临时力量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'NongMoZhongCai': '面 —— 造成 {Damage:diff()} 点伤害，给予 {Vulnerable:diff()} 层易伤。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'JuanZhou': '面 —— 抽 {Cards:diff()} 张牌。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'PoTianV5': '面 —— 对所有敌人造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'LiYaQianJun': '面 —— 造成 {Damage:diff()} 点伤害，获得 2 点临时力量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'MoJin': '面 —— 需手牌不多于 1 张才能打出。造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'KuangCao': '面 —— 受到 {BloodCost:diff()} 点伤害，抽 {Cards:diff()} 张牌。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'XuZhi': '0 费：抽 {Cards:diff()} 张牌。',
    'RunBi': '能力 —— 纯点流：每回合你打出的第一张「点」牌额外抽 {Draw:diff()} 张牌。',
    'DianJingZhiBi': '点 —— 0 费：抽 {Cards:diff()} 张牌。若本回合已打出 3 张以上点牌，额外获得 {Energy:diff()} 点能量。',
    'WanDianGuiYi': '点 —— 造成 {Damage:diff()} 点伤害，共 {Repeat:diff()} 次。',
    'ShuMiYouZhi': '点 —— 抽 {Cards:diff()} 张牌。若本回合已打出 4 张以上点牌（已触发惩罚），再抽 2 张。',
    'HaoLi': '点 —— 0 费：造成 {Damage:diff()} 点伤害。你每打出过 1 张点牌，此伤害 +2。',
    'DianShiChengJin': '点 —— 获得 2 点能量。',
    'MoShou': '点 —— 获得 {Block:diff()} 点格挡，你每打出过 1 张点牌额外 +3 格挡。',
    'LiTouZhiBeiV5': '能力 —— 纯线流：每回合开始时获得 2 点临时力量。',
    'TieHuaYinGou': '线 —— 造成 {Damage:diff()} 点伤害，获得 {Block:diff()} 点格挡，获得 3 点临时力量。',
    'ZhongFeng': '线 —— 获得 4 点临时力量与 4 点临时敏捷。',
    'TieXian': '线 —— 造成 {Damage:diff()} 点伤害。你每打出过 1 张线牌，此伤害 +3。',
    'XingYunLiuShui': '线 —— 抽 {Cards:diff()} 张牌，获得 2 点临时力量。',
    'BiLaoMoXiu': '线 —— 获得 5 点临时力量。',
    'QianJunYiBi': '线 —— 造成 {Damage:diff()} 点伤害，获得 4 点临时力量。',
    'PoTianAbility': '能力 —— 纯面流：你的「面」牌伤害额外 +{Bonus:diff()}。',
    'WanShanHongBian': '面 —— 对所有敌人造成 {Damage:diff()} 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'MoHai': '面 —— 抽 {Cards:diff()} 张牌，获得 3 点临时力量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'ShanGaoShuiChang': '面 —— 获得 {Block:diff()} 点格挡。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'ChangJuan': '面 —— 受到 {BloodCost:diff()} 点伤害，抽 {Cards:diff()} 张牌。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'LiTouWanXiang': '面 —— 造成 {Damage:diff()} 点伤害，获得 5 点临时力量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'KaiTianPiDi': '面 —— 造成 {Damage:diff()} 点伤害。若你的手牌为空，再对所有敌人造成 15 点伤害。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'JingShuiLiuShen': '面 —— 获得 {Block:diff()} 点格挡，获得 3 点临时敏捷。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'WanJieRuLinAncient': '先古 —— 抽 {Cards:diff()} 张牌，获得 3 点临时力量。 每场战斗首次打出时，将一张此牌的 0 费版本放入弃牌堆。',
    'WuMingZhiShi': '先古 —— 0 费：获得 2 点能量。 代价：已计入「斑驳乱点」的计数。',
    'TaDeLaiChu': '线 —— 获得 {Block:diff()} 点格挡，获得 2 点临时力量。 她的身世没人说得清，但她说的话总能让人多一分力气。',
    'HuoXuShiZhenDe': '面 —— 造成 {Damage:diff()} 点伤害，给予 {Vulnerable:diff()} 层易伤。 传闻有真有假。',
    'Mi': '点 —— 抽 {Cards:diff()} 张牌。若本回合已打出 2 张以上点牌，再抽 2 张。 「林」的身份一直是个谜。',
    'YiQiHeCheng': '能力 —— 你打出「面」牌时，本回合获得 {TempStr:diff()} 点临时力量。',
    'ZhangChiYouDu': '能力 —— 你打出「点」牌时，抽 1 张牌（每回合上限 {Cap:diff()} 次）。',
}

EN = {
    'DaJi': 'Deal {Damage:diff()} damage.',
    'FangYu': 'Gain {Block:diff()} Block.',
    'QiBi': '点 —— Deal {Damage:diff()} damage. If you this turn已打出过「点」牌, 此牌damage改为 14 点.',
    'YunBi': '线 —— Gain {Block:diff()} Block. 打出后this turnGain 1 点临时力量与 1 点临时敏捷, 并Draw 1 card(s)（千钧一线）.',
    'ChengFu': '面 —— Deal {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆（去年今日此门中）.',
    'QingDian': '点 —— Deal {Damage:diff()} damage. Draw {Cards:diff()} card(s).',
    'DianRan': '点 —— Gain {Block:diff()} Block. Draw {Cards:diff()} card(s).',
    'WeiMang': '点 —— 0 费：Deal {Damage:diff()} damage.',
    'LuoDian': '点 —— 0 费：Draw {Cards:diff()} card(s).',
    'ShuBi': '点 —— Draw {Cards:diff()} card(s).',
    'DianZhui': '点 —— Deal {Damage:diff()} damage. Draw {Cards:diff()} card(s).',
    'DianPo': '点 —— enemy Lose {Cards:diff()} Strength. Draw {StrengthLoss:diff()} card(s).',
    'HengXian': '线 —— Deal {Damage:diff()} damage, 给予 {Weak:diff()} stack(s)Weak. （千钧一线：另获 1 临时力量/敏捷 + Draw 1 张）.',
    'ShuXian': '线 —— Gain {Block:diff()} Block. Draw {Cards:diff()} card(s).',
    'GouXian': '线 —— Draw {Cards:diff()} card(s). （千钧一线：另获 1 临时力量/敏捷 + Draw 1 张）.',
    'LianXian': '线 —— Deal {Damage:diff()} damage, Gain {Block:diff()} Block. （千钧一线：另获 1 临时力量/敏捷 + Draw 1 张）.',
    'BiZhi': '线 —— Gain {Block:diff()} Block. Draw {Cards:diff()} card(s).',
    'ZhiBi': '线 —— Deal {Damage:diff()} damage, 给予 {Vulnerable:diff()} stack(s)Vulnerable.',
    'ChangXian': '线 —— Deal {Damage:diff()} damage. Draw {Cards:diff()} card(s). （千钧一线：另获 1 临时力量/敏捷 + Draw 1 张）.',
    'PoMian': '面 —— Deal {Damage:diff()} damage, 给予 {Vulnerable:diff()} stack(s)Vulnerable. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'DaMian': '面 —— Gain {Block:diff()} Block. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'MoMian': '面 —— Draw {Cards:diff()} card(s), Gain 1 Energy. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'ManFu': '面 —— Gain {Damage:diff()} Block, Deal 12 damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'KuoMian': '面 —— Deal to ALL enemies {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'ChenMo': '面 —— this turnGain {Cards:diff()} 点临时力量, Draw 2 card(s). per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'DianJing': '点 —— 0 费：Draw {Cards:diff()} card(s).',
    'DianShi': '点 —— Gain {Cards:diff()} Energy. Draw {Energy:diff()} card(s).',
    'YiDian': '点 —— 0 费：Deal {Damage:diff()} damage, 共 {Repeat:diff()} time(s).',
    'LuoMo': '点 —— Gain {Block:diff()} Block. Draw {Cards:diff()} card(s).',
    'ShuSan': '点 —— Draw {Cards:diff()} card(s).',
    'QianMiao': '点 —— Deal {Damage:diff()} damage, 给予 {Vulnerable:diff()} stack(s)Vulnerable.',
    'XiBi': '点 —— 0 费：Deal {Damage:diff()} damage.',
    'DianYin': '点 —— Draw {Cards:diff()} card(s). If you this turn已打出 3 张以上点牌, 额外Gain {Energy:diff()} Energy.',
    'MoDianV5': '点 —— Deal {Damage:diff()} damage. Gain 等同于this turn已打出点牌数 ×2 的Block.',
    'DianPoXuKong': '点 —— Deal {Damage:diff()} damage.',
    'HuiFeng': '点 —— 0 费：Lose {BloodCost:diff()} 点HP, Deal {Damage:diff()} damage.',
    'DianXianChengMian': '线 —— Draw {Cards:diff()} card(s). If this turn已打出 2 张以上点牌, 额外Gain {Energy:diff()} Energy.',
    'LiTouZhiBei': '线 —— Gain {Block:diff()} Block, 额外Gain 2 点临时力量. （千钧一线：另 +1 临时力/敏 + Draw 1 张）.',
    'YiBiHua': '线 —— Deal {Damage:diff()} damage, Gain {Block:diff()} Block.',
    'ZongHeng': '线 —— Gain 2 点临时力量与 2 点临时敏捷.',
    'XianTiao': '线 —— Deal {Damage:diff()} damage, Draw {Cards:diff()} card(s). （千钧一线：另 +1 临时力/敏 + Draw 1 张）.',
    'ZhiGuan': '线 —— Deal {Damage:diff()} damage. If this turn已打出 2 张以上线牌, damage翻倍.',
    'ChanSi': '线 —— Gain {Block:diff()} Block, 额外Gain 2 点临时敏捷.',
    'YunJinChengFeng': '线 —— Draw {Cards:diff()} card(s). （千钧一线：另 +1 临时力/敏 + Draw 1 张）.',
    'BiFengYiZhuan': '线 —— Gain 3 点临时力量.',
    'YiXianTian': '线 —— 需this turn已打出 3 张以上线牌才能打出. Deal {Damage:diff()} damage.',
    'ChuanZhenYinXian': '线 —— Deal {Damage:diff()} damage. you per 打出过 1 张线牌, 此damage +2.',
    'ChangQuZhiRu': '线 —— Deal {Damage:diff()} damage, 额外Gain 3 点临时力量.',
    'LiDaoHuiLiu': '线 —— Gain {Cards:diff()} 点临时力量, Draw 2 card(s).',
    'PoMoV5': '面 —— Deal to ALL enemies {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'DaPoMo': '面 —— Deal to ALL enemies {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'ManZhiYunYan': '面 —— Gain {Block:diff()} Block. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'WanHeQianYan': '面 —— Gain {Block:diff()} Block. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'MoYunTianChengV5': '面 —— Draw {Cards:diff()} card(s), Gain 2 点临时力量. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'NongMoZhongCai': '面 —— Deal {Damage:diff()} damage, 给予 {Vulnerable:diff()} stack(s)Vulnerable. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'JuanZhou': '面 —— Draw {Cards:diff()} card(s). per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'PoTianV5': '面 —— Deal to ALL enemies {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'LiYaQianJun': '面 —— Deal {Damage:diff()} damage, Gain 2 点临时力量. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'MoJin': '面 —— 需hand不多于 1 张才能打出. Deal {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'KuangCao': '面 —— Take {BloodCost:diff()} damage, Draw {Cards:diff()} card(s). per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'XuZhi': '0 费：Draw {Cards:diff()} card(s).',
    'RunBi': '能力 —— 纯点流：per turnyou 打出的第一张「点」牌额外Draw {Draw:diff()} card(s).',
    'DianJingZhiBi': '点 —— 0 费：Draw {Cards:diff()} card(s). If this turn已打出 3 张以上点牌, 额外Gain {Energy:diff()} Energy.',
    'WanDianGuiYi': '点 —— Deal {Damage:diff()} damage, 共 {Repeat:diff()} time(s).',
    'ShuMiYouZhi': '点 —— Draw {Cards:diff()} card(s). If this turn已打出 4 张以上点牌（已触发惩罚）, 再Draw 2 张.',
    'HaoLi': '点 —— 0 费：Deal {Damage:diff()} damage. you per 打出过 1 张点牌, 此damage +2.',
    'DianShiChengJin': '点 —— Gain 2 Energy.',
    'MoShou': '点 —— Gain {Block:diff()} Block, you per 打出过 1 张点牌额外 +3 Block.',
    'LiTouZhiBeiV5': '能力 —— 纯线流：per turn开始时Gain 2 点临时力量.',
    'TieHuaYinGou': '线 —— Deal {Damage:diff()} damage, Gain {Block:diff()} Block, Gain 3 点临时力量.',
    'ZhongFeng': '线 —— Gain 4 点临时力量与 4 点临时敏捷.',
    'TieXian': '线 —— Deal {Damage:diff()} damage. you per 打出过 1 张线牌, 此damage +3.',
    'XingYunLiuShui': '线 —— Draw {Cards:diff()} card(s), Gain 2 点临时力量.',
    'BiLaoMoXiu': '线 —— Gain 5 点临时力量.',
    'QianJunYiBi': '线 —— Deal {Damage:diff()} damage, Gain 4 点临时力量.',
    'PoTianAbility': '能力 —— 纯面流：you 的「面」牌damage额外 +{Bonus:diff()}.',
    'WanShanHongBian': '面 —— Deal to ALL enemies {Damage:diff()} damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'MoHai': '面 —— Draw {Cards:diff()} card(s), Gain 3 点临时力量. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'ShanGaoShuiChang': '面 —— Gain {Block:diff()} Block. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'ChangJuan': '面 —— Take {BloodCost:diff()} damage, Draw {Cards:diff()} card(s). per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'LiTouWanXiang': '面 —— Deal {Damage:diff()} damage, Gain 5 点临时力量. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'KaiTianPiDi': '面 —— Deal {Damage:diff()} damage. If you 的handis empty, 再Deal to ALL enemies 15 damage. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'JingShuiLiuShen': '面 —— Gain {Block:diff()} Block, Gain 3 点临时敏捷. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'WanJieRuLinAncient': '先古 —— Draw {Cards:diff()} card(s), Gain 3 点临时力量. per 场战斗首 time(s)打出时, 将一张此牌的 0 费版本放入弃牌堆.',
    'WuMingZhiShi': '先古 —— 0 费：Gain 2 Energy. 代价：已计入「斑驳乱点」的计数.',
    'TaDeLaiChu': '线 —— Gain {Block:diff()} Block, Gain 2 点临时力量. 她的身世没人说得清, 但她说的话总能让人多一分力气.',
    'HuoXuShiZhenDe': '面 —— Deal {Damage:diff()} damage, 给予 {Vulnerable:diff()} stack(s)Vulnerable. 传闻有真有假.',
    'Mi': '点 —— Draw {Cards:diff()} card(s). If this turn已打出 2 张以上点牌, 再Draw 2 张. 「林」的身份一直是个谜.',
    'YiQiHeCheng': '能力 —— you 打出「面」牌时, this turnGain {TempStr:diff()} 点临时力量.',
    'ZhangChiYouDu': '能力 —— you 打出「点」牌时, Draw 1 card(s)（per turn上限 {Cap:diff()} time(s)）.',
}

TITLES_ZH = {
    'DaJi': '打击',
    'FangYu': '防御',
    'QiBi': '起笔',
    'YunBi': '运笔',
    'ChengFu': '成幅',
    'QingDian': '轻点',
    'DianRan': '点染',
    'WeiMang': '微芒',
    'LuoDian': '落点',
    'ShuBi': '数笔',
    'DianZhui': '点缀',
    'DianPo': '点破',
    'HengXian': '横线',
    'ShuXian': '竖线',
    'GouXian': '勾线',
    'LianXian': '连线',
    'BiZhi': '笔直',
    'ZhiBi': '直笔',
    'ChangXian': '长线',
    'PoMian': '泼面',
    'DaMian': '大面',
    'MoMian': '磨面',
    'ManFu': '满幅',
    'KuoMian': '阔面',
    'ChenMo': '沉墨',
    'DianJing': '点睛',
    'DianShi': '点石',
    'YiDian': '一点',
    'LuoMo': '落墨',
    'ShuSan': '疏散',
    'QianMiao': '浅描',
    'XiBi': '细笔',
    'DianYin': '点引',
    'MoDianV5': '墨点',
    'DianPoXuKong': '点破虚空',
    'HuiFeng': '回锋',
    'DianXianChengMian': '点线成面',
    'LiTouZhiBei': '力透纸背',
    'YiBiHua': '一笔画',
    'ZongHeng': '纵横',
    'XianTiao': '线条',
    'ZhiGuan': '直贯',
    'ChanSi': '缠丝',
    'YunJinChengFeng': '运斤成风',
    'BiFengYiZhuan': '笔锋一转',
    'YiXianTian': '一线天',
    'ChuanZhenYinXian': '穿针引线',
    'ChangQuZhiRu': '长驱直入',
    'LiDaoHuiLiu': '力道回流',
    'PoMoV5': '泼墨',
    'DaPoMo': '大泼墨',
    'ManZhiYunYan': '满纸云烟',
    'WanHeQianYan': '万壑千岩',
    'MoYunTianChengV5': '墨韵天成',
    'NongMoZhongCai': '浓墨重彩',
    'JuanZhou': '卷轴',
    'PoTianV5': '泼天',
    'LiYaQianJun': '力压千钧',
    'MoJin': '墨尽',
    'KuangCao': '狂草',
    'XuZhi': '续纸',
    'RunBi': '润笔',
    'DianJingZhiBi': '点睛之笔',
    'WanDianGuiYi': '万点归一',
    'ShuMiYouZhi': '疏密有致',
    'HaoLi': '毫厘',
    'DianShiChengJin': '点石成金',
    'MoShou': '墨守',
    'LiTouZhiBeiV5': '力透纸背',
    'TieHuaYinGou': '铁画银钩',
    'ZhongFeng': '中锋',
    'TieXian': '铁线',
    'XingYunLiuShui': '行云流水',
    'BiLaoMoXiu': '笔老墨秀',
    'QianJunYiBi': '千钧一笔',
    'PoTianAbility': '泼天',
    'WanShanHongBian': '万山红遍',
    'MoHai': '墨海',
    'ShanGaoShuiChang': '山高水长',
    'ChangJuan': '长卷',
    'LiTouWanXiang': '力透万象',
    'KaiTianPiDi': '开天辟地',
    'JingShuiLiuShen': '静水流深',
    'WanJieRuLinAncient': '万界如林',
    'WuMingZhiShi': '无名之始',
    'TaDeLaiChu': '她的来处',
    'HuoXuShiZhenDe': '或许是真的',
    'Mi': '谜',
    'YiQiHeCheng': '一气呵成',
    'ZhangChiYouDu': '张弛有度',
}

TITLES_EN = {
    'DaJi': '打击',
    'FangYu': '防御',
    'QiBi': '起笔',
    'YunBi': '运笔',
    'ChengFu': '成幅',
    'QingDian': '轻点',
    'DianRan': '点染',
    'WeiMang': '微芒',
    'LuoDian': '落点',
    'ShuBi': '数笔',
    'DianZhui': '点缀',
    'DianPo': '点破',
    'HengXian': '横线',
    'ShuXian': '竖线',
    'GouXian': '勾线',
    'LianXian': '连线',
    'BiZhi': '笔直',
    'ZhiBi': '直笔',
    'ChangXian': '长线',
    'PoMian': '泼面',
    'DaMian': '大面',
    'MoMian': '磨面',
    'ManFu': '满幅',
    'KuoMian': '阔面',
    'ChenMo': '沉墨',
    'DianJing': '点睛',
    'DianShi': '点石',
    'YiDian': '一点',
    'LuoMo': '落墨',
    'ShuSan': '疏散',
    'QianMiao': '浅描',
    'XiBi': '细笔',
    'DianYin': '点引',
    'MoDianV5': '墨点',
    'DianPoXuKong': '点破虚空',
    'HuiFeng': '回锋',
    'DianXianChengMian': '点线成面',
    'LiTouZhiBei': '力透纸背',
    'YiBiHua': '一笔画',
    'ZongHeng': '纵横',
    'XianTiao': '线条',
    'ZhiGuan': '直贯',
    'ChanSi': '缠丝',
    'YunJinChengFeng': '运斤成风',
    'BiFengYiZhuan': '笔锋一转',
    'YiXianTian': '一线天',
    'ChuanZhenYinXian': '穿针引线',
    'ChangQuZhiRu': '长驱直入',
    'LiDaoHuiLiu': '力道回流',
    'PoMoV5': '泼墨',
    'DaPoMo': '大泼墨',
    'ManZhiYunYan': '满纸云烟',
    'WanHeQianYan': '万壑千岩',
    'MoYunTianChengV5': '墨韵天成',
    'NongMoZhongCai': '浓墨重彩',
    'JuanZhou': '卷轴',
    'PoTianV5': '泼天',
    'LiYaQianJun': '力压千钧',
    'MoJin': '墨尽',
    'KuangCao': '狂草',
    'XuZhi': '续纸',
    'RunBi': '润笔',
    'DianJingZhiBi': '点睛之笔',
    'WanDianGuiYi': '万点归一',
    'ShuMiYouZhi': '疏密有致',
    'HaoLi': '毫厘',
    'DianShiChengJin': '点石成金',
    'MoShou': '墨守',
    'LiTouZhiBeiV5': '力透纸背',
    'TieHuaYinGou': '铁画银钩',
    'ZhongFeng': '中锋',
    'TieXian': '铁线',
    'XingYunLiuShui': '行云流水',
    'BiLaoMoXiu': '笔老墨秀',
    'QianJunYiBi': '千钧一笔',
    'PoTianAbility': '泼天',
    'WanShanHongBian': '万山红遍',
    'MoHai': '墨海',
    'ShanGaoShuiChang': '山高水长',
    'ChangJuan': '长卷',
    'LiTouWanXiang': '力透万象',
    'KaiTianPiDi': '开天辟地',
    'JingShuiLiuShen': '静水流深',
    'WanJieRuLinAncient': '万界如林',
    'WuMingZhiShi': '无名之始',
    'TaDeLaiChu': '她的来处',
    'HuoXuShiZhenDe': '或许是真的',
    'Mi': '谜',
    'YiQiHeCheng': '一气呵成',
    'ZhangChiYouDu': '张弛有度',
}
